### ISSUE TITLE
[please add] Morpheus (server-side)

### ISSUE THREAD

**Issue by Tenmaver** [kreezxil/Svet-Draku#14]
# Mod Nominated for Adding*
Mod Name: Morpheus 
Mod Link: https://www.curseforge.com/minecraft/mc-mods/morpheus

# Reason for Nomination

Reason: Sleep-vote system for server playing.

**Comment by kreezxil** [comment]
The night is just as important as the daytime. Sleeping voting systems ruin
the night time experience. This was especially true when astralsorcery was
in the pack. You need to know that your base is secure against the mobs and
what better way to do that than seeing if it can survive the night.
