### ISSUE TITLE
[please add] Woot

### ISSUE THREAD

**Issue by Tenmaver** [kreezxil/Svet-Draku#16]
# Mod Nominated for Adding*
Mod Name: Woot
Mod Link: https://www.curseforge.com/minecraft/mc-mods/woot

# Reason for Nomination

Reason: Mob farms for items that would not lag server/client because it doesnt actually spawn a entity it just generates the loot&xp. It may not fit the style, but it seems perfomnce friendly. Dont know about the configs tho, maybe its not configurable what you can farm.

**Comment by kreezxil** [comment]
Woot is a high end tech mod and basically takes the pack beyond the tech level provided for by Immersive Engineering.
