### ISSUE TITLE
[please add] Craftpresence

### ISSUE THREAD

**Issue by Tenmaver** [kreezxil/Svet-Draku#17]
# Mod Nominated for Adding*
Mod Name: Craftpresence or any mod that adds discord integration
Mod Link:https://www.curseforge.com/minecraft/mc-mods/craftpresence

# Reason for Nomination

Reason: So everyone can see what pack are you playing, seems great shows alot of info like where you are how long did you played if you are on SP or MP etc. Maybe it would draw more attention all across discord.

**Comment by kreezxil** [comment]
done, still up to the player to configure this one. tho.
