### ISSUE TITLE
[please replace] Featured servers with ITLT

### ISSUE THREAD

**Issue by Tenmaver** [kreezxil/Svet-Draku#19]
# Mod Nominated for REPLACEl
Mod Name: Featured Server
Replace with: ITS THE LITTLE THINGS - https://www.curseforge.com/minecraft/mc-mods/its-the-little-things

# Reason for Nomination

Reason: You can set the same things that featured server does in its the little things + in its the little things you can set the icon of the modpack on toolbar/name of the window in Windows ETC (all is in config)

**Comment by kreezxil** [comment]
except there is one major difference. On each update, ITLT will wipe all
the custom entries for other servers, FEATURED SERVERS will not.

**Comment by kreezxil** [comment]
and I use randompatches for the other parts of ITLT, plus RP does phenomenally more than ITLT like for instance allowing me to make server connect time be 1800 ticks or 5 minutes long, perfect for bad internet.
