### ISSUE TITLE
[please add] ArchitectureCraft OR Blockcraftery

### ISSUE THREAD

**Issue by Tenmaver** [kreezxil/Svet-Draku#21]
# Mod Nominated for Adding*
Mod Name: ArchitectureCraft OR Blockcraftery
Mod Link: https://www.curseforge.com/minecraft/mc-mods/architecturecraft-tridev or https://www.curseforge.com/minecraft/mc-mods/blockcraftery

# Reason for Nomination

Reason: You can build almost anything from this, ALOT of nice shapes from any materials. Posted 2 mods in one because i think both are useless, if one of these should be added it should be only one of these.

**Comment by kreezxil** [comment]
both added, next time don't put two in a ticket, each request to it's own ticket please
