### ISSUE TITLE
Resources packs - permission granted

### ISSUE THREAD

**Issue by Tenmaver** [kreezxil/Svet-Draku#24]
![permissiongrantedyay](https://user-images.githubusercontent.com/63076754/78503416-b711fb80-7766-11ea-9836-46dc353fd305.png)
link: https://user-images.githubusercontent.com/63076754/78503416-b711fb80-7766-11ea-9836-46dc353fd305.png

links for DRAGONS resource packs: 
https://www.dropbox.com/s/8hp1f1wfkid5t2z/GoT%20Dragons.zip?dl=1
https://www.dropbox.com/s/sh3czo6q1x4om8q/Better%20Dragons%201.8%2B.zip?dl=1
https://www.dropbox.com/s/3ttls0aun22hqis/Wild%20Dragons%201.8%2B.zip?dl=1

**Comment by kreezxil** [comment]
added for now, hopefully cf tells me how to handle the perms, I've put the images of the perms in the resourcepacks folder, maybe they'll see that and accept it.
