### ISSUE TITLE
Don't add Ender IO & TechGuns to Svet Draku

### ISSUE THREAD

**Issue by ThaneFenrir** [kreezxil/Svet-Draku#3]
**Is your feature request related to a problem? Please describe.**
Ender IO doesn't add anything that is not already in the pack ( excepts soul vials ) & ( Permanent Soul Bound ) so in total it doesn't really add anything that furthers the pack. Thermal Dynamics & RFTOOLS already had a power source and and ways to transfer power and items. Now TechGuns only added guns ( that are useless ) and armor ( also creative flight ) overall didn't add anything that helps. ( I guess you could say " But it added armor that made me go fast..." or " It gave me step assist and it let me jump higher" ) ( In response to that " GROW UP, I'm trying to help " ) 

**Describe the solution you'd like**
Have a server poll and let the community decide ( if possible ) to remove said mods... 

**Describe alternatives you've considered**

**Additional context**

**Comment by kreezxil** [comment]
remvoed
