### ISSUE TITLE
[consider] Horse Tweaks

### ISSUE THREAD

**Issue by Tenmaver** [kreezxil/Svet-Draku#31]
# Mod to consider*
Mod Name: Horse Tweaks
Mod Link: https://www.curseforge.com/minecraft/mc-mods/horse-tweaks

# Reason for Nomination

Reason: More saddles for horses, like water walking etc etc, maybe too OP or incompatible with other modded animals that wear saddles.

**Comment by kreezxil** [comment]
yeah it's a bit op
