### ISSUE TITLE
book of skills

### ISSUE THREAD

**Issue by Tenmaver** [kreezxil/Svet-Draku#34]
Add book of skills as starting item
itemid: 4322

**Comment by kreezxil** [comment]
you don't understand, prior to 1.12.2 item ids were numbers, they're no longer numbers even tho jei shows them as numbers in the parens.

this is an item id now
```
improvableskills:skills_book
```
aka
```
modname:itemname
```
![image](https://user-images.githubusercontent.com/3880072/78949863-92819080-7a92-11ea-8960-c505bf64fd39.png)
