### ISSUE TITLE
Item Scroller opens menu in inventory while searching JEI

### ISSUE THREAD

**Issue by Diamond200512** [kreezxil/Svet-Draku#37]
The mod Item Scroller has a default keybind that pulls a menu up in your inventory. Even if you are searching JEI. The key is S

**Comment by kreezxil** [comment]
and they just announced they won't be maintaining this anymore either. dang. it's the last update that is causing this. Did you fix it by remapping the keybind at all?

**Comment by Diamond200512** [comment]
you can I just didnt do it yet. i found out what it was because of the keybinds

**Comment by kreezxil** [comment]
fixed
