### ISSUE TITLE
ice&fire questline ideas

### ISSUE THREAD

**Issue by Tenmaver** [kreezxil/Svet-Draku#39]
ice and fire questline:
1) "Knowledge is Power" acquire BESTIARY - find a dragon nest to obtain manuscript and craft bestiary to learn more about the creatures of i&f! - reward = 100 xp
2) "Books,books books..." Craft Lectern for you bestiary and combine it with manuscripts to add more pages to your bestiary! Reward: 50 xp
3) "A Song That Kills" - Kill a siren. reward: 10 iron ingots
4) "I said you will come with me! - Obtain a iron chain - Reward: 5 gold ingots
5) "Dont look at her!" - Kill a Gorgon. Reward: 3 diamonds
6) "Is anybody home?" - Kill a Cyclops. Reward: 3 diamonds
7) "Enemy of the sea" - Kill a Sea Serpent. Reward: 8 dragon growth
8) "Aaaah, WHAT IS THIS?!" - Kill a Death Worm. Reward: 4 dragon growth
9) "Fly, bird fly! - Kill a Stymphalian Bird Reward: 4 dragon growth
10) "Who are you again?" - Kill a Troll. Reward: 3 emeralds
11) "Ready to catch!" - Craft a Jar to capture pixie! Reward: 50 xp
12) "A new friend of mine!" - Craft a Cake to tame a pixie! Reward: 100xp
13) "Ewwww, it lays eggs!" - Obtain a Myrmex Egg Reward: 3 emerald
14) "A majestic buddy!" - Obtain 5 Rabbit Foots to tame a Hippogryph! Reward: Iron Hippogryph Armor
15) "Weird...chicken?" - Obtain a Rotten Egg to hatch a Cockatrice! Reward: 4 dragon growth
16) "Love and Feathers!" - Craft 2 cookies to succesfully breed a pair of Amphitheres! Reward: 50 xp
17) "Who wants some stew?" Craft 2 rabbit stew to succesfully breed a pair of Hippogryphs! Reward: 50 xp
18) "Fish Love?" Obtain 2 prismarine crystals to succesfully breed a pair of Hippocampus! Reward: 50 xp
19) "Dragon Slayer" Kill any living WILD dragon! Reward: 8 emeralds
20) "Just a little sample" Obtain Dragon Blood by using empty glass bottles on a dead dragon. Reward: 16 Sapphire
21) "Dragon...tools?" Craft any Dragonbone tool - Reward: 8 Sapphire
22) "A friend for life" Obtain any Dragon Egg. Reward: 16 diamonds
23) "A little help over here?" Craft a Dragon Meal to make growth of you dragon faster - Reward: 8 Sapphire
24) "Obey me!" Craft Dragon Command Staff and Dragon flute to control the dragon! Reward: 4 Sapphire
25) "Baby Dragon?" Craft one of the Lily Mixtures to breed two dragons! Reward: 3 Sapphire
26) "Never, enough...ARMOR!" Craft any dragon armor set to protect your dragon! Reward: 32 Gold Ingot
27) "Dragonsteel baby!" Use bestiary to learn how to make dragonforge and create Dragonsteel Ingot! Reward: 16 dragon growth

**Comment by Diamond200512** [comment]
for any living dragon does that mean you could kill someone's pet

**Comment by Tenmaver** [comment]
> for any living dragon does that mean you could kill someone's pet

no wtf man. edited :D

**Comment by Tenmaver** [comment]
moved to: https://github.com/kreezxil/Svet-Draku/issues/41
