### ISSUE TITLE
Dragons detect from too far

### ISSUE THREAD

**Issue by Diamond200512** [kreezxil/Svet-Draku#46]
Dragons detect players walking around while underground, they then break out of the ground and attack players who didn't see the dragon until it came out from underground

**Comment by kreezxil** [comment]
This is by design, you're supposed to be scared of dragons.

**Comment by rwatson1** [comment]
And you don't have to see them...turn your sound on, they ain't exactly quiet. My strategy is hear roar, turn around, run away. Besides that it certainly gives the game a nice thrill.
