### ISSUE TITLE
Otherwordly tears from witchery don't craft

### ISSUE THREAD

**Issue by Diamond200512** [kreezxil/Svet-Draku#49]
Th otherworldly tears from the bewitchment mod have a recipe but do not craft when put in the correct order and station

**Comment by kreezxil** [comment]
see if the issue has been reported, if not report it and bring the link to
the issue here.

**Comment by Diamond200512** [comment]
I just reported on their github, and it isnt just the tears it is everything you can make in the distillery

**Comment by Diamond200512** [comment]
found the problem, it cant decide wether its powered or not by the altar so I just placed it on altar
