### ISSUE TITLE
journeymap fatal error

### ISSUE THREAD

**Issue by Diamond200512** [kreezxil/Svet-Draku#50]
I entered the nether and got a bunch of errors from journeymap.
logs 
[2020-05-07-4.log.gz](https://github.com/kreezxil/Svet-Draku/files/4596975/2020-05-07-4.log.gz)
I tried pasting it in the github paste service you gave me kreez but it doesnt create it., it stops responding

**Comment by kreezxil** [comment]
it stops responding because it's uploading

**Comment by kreezxil** [comment]
also if your client doesn't act wonky or crash, I don't want the logs. we
don't process warnings, nobody does.

**Comment by kreezxil** [comment]
Looked at your log.

I'm not responsible for your turnip running out of memory.

You need to learn to read your logs, don't just freak out when you see "errors", Be like DR. Who when he sees a dalek. His companions freak out, he does not.

![image](https://user-images.githubusercontent.com/3880072/81487276-e4980c00-9220-11ea-9181-4536528a170f.png)
