### ISSUE TITLE
[please add] OTG + Bundle Biome 

### ISSUE THREAD

**Issue by Tenmaver** [kreezxil/Svet-Draku#8]
# Mod Nominated for Adding*
Mod Name: OTG + Biome Bundle
Mod Link: https://www.curseforge.com/minecraft/mc-mods/open-terrain-generator + https://www.curseforge.com/minecraft/mc-mods/biome-bundle

# Reason for Nomination

Reason: I feel like the vanilla world gen is what we all know, the OTG with Biome Bundle is awesome used it for some time, dont know if its compatible with generating structures from I&F and dungeons mods would need checking

**Comment by kreezxil** [comment]
there are other terrain generators I'd rather use, I have had issues with
this one on a server.

**Comment by kreezxil** [comment]
we'll try it

**Comment by kreezxil** [comment]
decided against it because of the 2gb+ footprint they openly admit to

**Comment by kreezxil** [comment]
added RTG instead
